name: golangci-lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  lint:
    name: Run golangci lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b #v2.4.0
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 #v2.1.5
        with:
          go-version: '1.18'
      - uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5
        with:
          only-new-issues: true
